# Generated by Django 4.2.5 on 2023-11-11 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakedgood',
            name='baked_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
